# Generated by Django 2.0.6 on 2018-06-23 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(default='', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('price', models.IntegerField(default=0)),
                ('small_photo', models.ImageField(null=True, upload_to='')),
                ('big_photo', models.ImageField(null=True, upload_to='')),
                ('is_enabled', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_really_hot', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Category')),
            ],
        ),
    ]
